name: Android Build & Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating a release

    steps:
      - name: 🧾 Checkout Code
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: 🔐 Give gradlew execute permission
        run: chmod +x ./gradlew

      - name: 🏗️ Build Debug APK
        run: ./gradlew assembleDebug

      - name: 📦 Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: animals-pop-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: 🚀 Create GitHub Release & Upload APK
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          artifacts: app/build/outputs/apk/debug/app-debug.apk
          token: ${{ secrets.RELEASE_TOKEN }}  # ✅ This should be your secure PAT stored in repo secrets
          generateReleaseNotes: true
          makeLatest: legacy
          replacesArtifacts: true
