name: 🔧 CI Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Just Say Hello 👋
        run: echo "GitHub Actions is working!"
